version: '3.8'

networks:
  app-tier:
    driver: bridge
    name: app-tier

services:
  article:
    container_name: article
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/article
    ports:
      - 8000:8000
    depends_on:
      - article_db
    networks:
      - app-tier

  article_db:
    image: mysql:5.7.22
    container_name: article_db
    environment:
      MYSQL_DATABASE: article
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
    networks:
      - app-tier
